/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systems.tech247.clockinutil;

import java.awt.BorderLayout;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.Date;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.view.OutlineView;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.WindowManager;
import systems.tech247.hr.OrganizationUnits;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//systems.tech247.clockinutil//DepartmentAttendance//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "DepartmentAttendanceTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "editor", openAtStartup = true, roles = {"ta"})
@ActionID(category = "Window", id = "systems.tech247.clockinutil.DepartmentAttendanceTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_DepartmentAttendanceAction",
        preferredID = "DepartmentAttendanceTopComponent"
)
@Messages({
    "CTL_DepartmentAttendanceAction=DepartmentAttendance",
    "CTL_DepartmentAttendanceTopComponent=Department Attendance",
    "HINT_DepartmentAttendanceTopComponent=This is a DepartmentAttendance window"
})
public final class DepartmentAttendanceTopComponent extends TopComponent implements ExplorerManager.Provider, LookupListener {

    Lookup.Result<OrganizationUnits> departmentResult = WindowManager.getDefault().findTopComponent("AttendanceTopComponent").getLookup().lookupResult(OrganizationUnits.class);
    ExplorerManager em = UtilZKClockin.departmentAttendance;
    OrganizationUnits department = null;
    public DepartmentAttendanceTopComponent() {
        initComponents();
        setName(Bundle.CTL_DepartmentAttendanceTopComponent());
        setToolTipText(Bundle.HINT_DepartmentAttendanceTopComponent());
        vpanel.setLayout(new BorderLayout());
        
        //Use todays Date, User can change to what s/he wants
        jdcAttendanceDate.setDate(new Date());
        jdcAttendanceDate.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if(evt.getSource()==jdcAttendanceDate && "date".equals(evt.getPropertyName())){
                    UtilZKClockin.loadDepartmentAttendance(department, jdcAttendanceDate.getDate());
                }
            }
        });
        OutlineView ov = new OutlineView("Employee Name");
        ov.getOutline().setRootVisible(false);
        ov.addPropertyColumn("empCode", "Clockin ID");
        ov.addPropertyColumn("timeIN", "Time IN");
        ov.addPropertyColumn("timeOUT", "Time OUT");
        ov.addPropertyColumn("shift", "SHIFT");
        ov.addPropertyColumn("hours", "Hours Worked");
        vpanel.add(ov);
        departmentResult.addLookupListener(this);
        resultChanged(new LookupEvent(departmentResult));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        vpanel = new javax.swing.JPanel();
        jdcAttendanceDate = new com.toedter.calendar.JDateChooser();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(DepartmentAttendanceTopComponent.class, "DepartmentAttendanceTopComponent.jLabel1.text")); // NOI18N

        vpanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout vpanelLayout = new javax.swing.GroupLayout(vpanel);
        vpanel.setLayout(vpanelLayout);
        vpanelLayout.setHorizontalGroup(
            vpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        vpanelLayout.setVerticalGroup(
            vpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 159, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdcAttendanceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jdcAttendanceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JDateChooser jdcAttendanceDate;
    private javax.swing.JPanel vpanel;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return em;
    }

    @Override
    public void resultChanged(LookupEvent le) {
        Lookup.Result<OrganizationUnits> result = (Lookup.Result<OrganizationUnits>)le.getSource();
        for(OrganizationUnits unit : result.allInstances()){
            //Load the employees in that department with their clockins
            department = unit;
            UtilZKClockin.loadDepartmentAttendance(department, jdcAttendanceDate.getDate());
        }
    }
}
